### ISSUE TITLE
Can't close launcher normally [Linux, GNOME]

### ISSUE THREAD

**Issue by Elijahrane** [space-wizards/SS14.Launcher#37] opened 2021-12-24 20:12 UTC
Attempting to close the launcher through normal methods (the 'close' window decoration or the close window shortcut) does not close the program for me; it just makes it hang. I have to do `pkill SS14.Launcher` to close it. There's nothing in the log when this happens (beyond what happens every time you run the program), so I have decided not to attach one.

Reproduction Steps:
1. Open the launcher
2. Attempt to close it using the 'close' button or a close window keyboard shortcut
3. The launcher does not close but just becomes unresponsive (90% of the time, it very very rarely will actually close for me)

Output of uname -a:
`Linux rane-pc 5.15.5-76051505-generic #202111250933~1638201579~20.04~09f1aa7-Ubuntu SMP Tue Nov 30 02: x86_64 x86_64 x86_64 GNU/Linux`

Distribution: Pop! OS 20.04
Gnome Version: 3.36.8
X server version: 1.20.13
NVIDIA driver version: 470.86
Graphics: Nvidia MX130 with proprietary drivers for everything, iGPU disabled
CPU: Intel® Core™ i5-7200U CPU

**Comment by PJB3005** [comment] 2021-12-25 12:54
I think the named pipe stream thing may just be broken on Linux.

**Comment by NicoSGF64** [comment] 2022-02-03 21:36
I had the same problem, in my case in Xfce.

After enabling logging, I found the following error in the client-stderr.log:
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)

One quick search about the error and we end up on the [ArchWiki article for Telegram](https://wiki.archlinux.org/title/Telegram), where the Wiki recommends installing [realtime-privileges](https://wiki.archlinux.org/title/Realtime_process_management#Configuring_PAM) and adding yourself to the realtime group. 

One restart later and ta-da! The problem is almost gone (still happens from time to time). I'd suggest that you try that solution out.

**Relevant info:**
Launcher used: Stand-alone version
Distro: Arch Linux
Linux Version: 5.16.5-arch1-1
Xfce Version: 4.16
WM: Xfwm 4.16.1 (revision 5f61a84ad)
Xorg version: 21.1.3-1
GPU: AMD RX 580
GPU drivers: amdgpu, xf86-video-amdgpu (21.0.0-2)
CPU: AMD Ryzen 3 3200G

**Comment by PJB3005** [comment] 2022-02-25 21:45
I have no idea how changing thread priority for the audio thread to realtime fixes it, but that should be 100% completely unrelated.

**Comment by PJB3005** [comment] 2022-02-25 21:46
The actual issue here is a deadlock which Avalonia fixed in 0.10.12 by the way, working on it.

**Closed** 2022-04-17 09:11 UTC
