### ISSUE TITLE
2FA screen title broken

### ISSUE THREAD

**Issue by tosatur** [space-wizards/SS14.Launcher#173] opened 2024-08-10 08:53 UTC
Doesn't have the localised title text for any language

![image](https://github.com/user-attachments/assets/8c79b1a4-f398-45d7-820a-862e47aa048f)

**Comment by PJB3005** [comment] 2024-08-10 20:32
Duplicate of #158, I just haven't deployed a new launcher version yet.

**Closed by PJB3005** 2024-08-10 20:32 UTC
